$(document).ready(function(){

    var quote = new Array();
    quote[0] = 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. <span>-Thomas A. Edison</span>';
    quote.push('You are never too old to set another goal or to dream a new dream. <span>-C.S. Lewis</span>');
    quote.push('Try not to become a man of success but a man of value. <span>-Albert Einstein</span>');
    quote.push('Doubt whom you will, but never yourself. <span>-Christian Nestell Bovee</span>');
    quote.push('Every artist was first an amateur. <span>-Ralph Waldo Emerson</span>');
    quote.push('In any project the important factor is your belief. Without belief, there can be no successful outcome. <span>-William James</span>');
    quote.push('We can do anything we want to do if we stick to it long enough. <span>-Helen Keller</span>');
    quote.push('No great man ever complains of want of opportunities. <span>-Ralph Waldo Emerson</span>');
    quote.push('We are all faced with a series of great opportunities - brilliantly disguised as insoluable problems. <span>-John Gardner</span></span>');
    quote.push('First say to yourself what you would be; and then do what you have to do. <span>-Epictetus</span>');
    quote.push('You miss 100% of the shots you don\'t take.  <span>-Wayne Gretzky</span>');
    quote.push('Take calculated risks. That is quite different from being rash. <span>-George S. Patton</span>');
    quote.push('Storms make oaks take roots. <span>-Proverb</span>');
    quote.push('Well begun is half done. <span>-Greek Proverb</span>');
    quote.push('And all may do what has by man been done. <span>-Edward Young</span>');
    quote.push('Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us. <span>-Samuel Smiles</span>');
    quote.push('Work spares us from three evils: boredom, vice, and need. <span>-Voltaire</span>');
    quote.push('Do not wait to strike till the iron is hot; but make it hot by striking. <span>-William B. Sprague</span>');
    quote.push('Fortune favors the brave. <span>-Publius Terence</span>');
    quote.push('When the best things are not possible, the best may be made of those that are. <span>-Richard Hooker</span>');
    quote.push('In doubtful matters boldness is everything. <span>-Publilius Syrus</span>');
    quote.push('Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.  <span>–Robert Frost</span>');
    quote.push('I attribute my success to this: I never gave or took any excuse. <span>–Florence Nightingale</span>');
    quote.push('The most difficult thing is the decision to act, the rest is merely tenacity. <span>–Amelia Earhart</span>');
    quote.push('Every strike brings me closer to the next home run. <span>–Babe Ruth</span>');
    quote.push('Definiteness of purpose is the starting point of all achievement. <span>–W. Clement Stone</span>');
    quote.push('We must balance conspicuous consumption with conscious capitalism. <span>–Kevin Kruse</span>');
    quote.push('Life is what happens to you while you’re busy making other plans. <span>–John Lennon</span>');
    quote.push('We become what we think about. <span>–Earl Nightingale</span>');
    quote.push('Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover. <span>–Mark Twain</span>');
    quote.push('Life is 10% what happens to me and 90% of how I react to it. <span>–Charles Swindoll</span>');
    quote.push('The most common way people give up their power is by thinking they don’t have any. <span>–Alice Walker</span>');
    quote.push('The best time to plant a tree was 20 years ago. The second best time is now. <span>–Chinese Proverb</span>');
    quote.push('An unexamined life is not worth living. <span>-Socrates</span>');
    quote.push('Eighty percent of success is showing up. <span>-Woody Allen</span>');
    quote.push('Your time is limited, so don’t waste it living someone else’s life. <span>–Steve Jobs</span>');
    quote.push('Winning isn’t everything, but wanting to win is. <span>-Vince Lombardi</span>');
    quote.push('I am not a product of my circumstances. I am a product of my decisions. <span>–Stephen Covey</span>');
    quote.push('Every child is an artist.  The problem is how to remain an artist once he grows up. <span>–Pablo Picasso</span>');
    quote.push('You can never cross the ocean until you have the courage to lose sight of the shore. <span>–Christopher Columbus</span>');
    quote.push('I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. <span>-Maya Angelou</span>');
    quote.push('Either you run the day, or the day runs you. <span>–Jim Rohn</span>');
    quote.push('Whether you think you can or you think you can’t, you’re right. <span>–Henry Ford</span>');
    quote.push('The two most important days in your life are the day you are born and the day you find out why. <span>–Mark Twain</span>');
    quote.push('Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it. <span>–Johann Wolfgang von Goethe</span>');
    quote.push('The best revenge is massive success. <span>–Frank Sinatra</span>');
    quote.push('People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily. <span>–Zig Ziglar</span>');
    quote.push('Life shrinks or expands in proportion to one’s courage. <span>–Anais Nin</span>');
    quote.push('If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced. <span>–Vincent Van Gogh</span>');
    quote.push('There is only one way to avoid criticism: do nothing, say nothing, and be nothing. <span>–Aristotle</span>');
    quote.push('The only person you are destined to become is the person you decide to be. <span>–Ralph Waldo Emerson</span>');
    quote.push('Go confidently in the direction of your dreams.  Live the life you have imagined. <span>-Henry David Thoreau</span>');
    quote.push('When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me. <span>-Erma Bombeck</span>');
    quote.push('Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.  <span>-Booker T. Washington</span>');
    quote.push('Certain things catch your eye, but pursue only those that capture the heart. <span>-Ancient Indian Proverb</span>');
    quote.push('Believe you can and you’re halfway there. <span>-Theodore Roosevelt</span>');
    quote.push('Everything you’ve ever wanted is on the other side of fear. <span>-George Addair</span>');
    quote.push('We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. <span>-Plato</span>');
    quote.push('Teach thy tongue to say, “I do not know,” and thous shalt progress. <span>-Maimonides</span>');
    quote.push('Start where you are. Use what you have.  Do what you can. <span>-Arthur Ashe</span>');
    quote.push('Fall seven times and stand up eight. <span>–Japanese Proverb</span>');
    quote.push('When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. <span>–Helen Keller</span>');
    quote.push('Everything has beauty, but not everyone can see. <span>–Confucius</span>');
    quote.push('How wonderful it is that nobody need wait a single moment before starting to improve the world. <span>–Anne Frank</span>');
    quote.push('When I let go of what I am, I become what I might be. <span>–Lao Tzu</span>');
    quote.push('Life is not measured by the number of breaths we take, but by the moments that take our breath away. <span>–Maya Angelou</span>');
    quote.push( 'Happiness is not something readymade.  It comes from your own actions. <span>–Dalai Lama</span>');
    quote.push('If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. <span>–Sheryl Sandberg</span>');
    quote.push('Too many of us are not living our dreams because we are living our fears. <span>–Les Brown</span>');
    quote.push('You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground. <span>–Unknown</span>');
    quote.push('Challenges are what make life interesting and overcoming them is what makes life meaningful. <span>–Joshua J. Marine</span>');
    quote.push('If you want to lift yourself up, lift up someone else. <span>–Booker T. Washington</span>');
    quote.push('I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. <span>–Leonardo da Vinci</span>');
    quote.push('Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless. <span>–Jamie Paolinetti</span>');
    quote.push('You take your life in your own hands, and what happens? A terrible thing, no one to blame. <span>–Erica Jong</span>');
    quote.push('What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. <span>–Bob Dylan</span>');
    quote.push('I didn’t fail the test. I just found 100 ways to do it wrong. <span>–Benjamin Franklin</span>');
    quote.push('In order to succeed, your desire for success should be greater than your fear of failure. <span>–Bill Cosby</span>');
    quote.push('A person who never made a mistake never tried anything new. <span>-Albert Einstein</span>');
    quote.push('The person who says it cannot be done should not interrupt the person who is doing it. <span>–Chinese Proverb</span>');
    quote.push("The person who says it cannot be done should not interrupt the person who is doing it. <span>–Chinese Proverb</span>");
    quote.push("There are no traffic jams along the extra mile. <span>–Roger Staubach</span>");
    quote.push("It is never too late to be what you might have been. <span>–George Eliot</span>");
    quote.push("I would rather die of passion than of boredom. <span>–Vincent van Gogh</span>");
    quote.push("A truly rich man is one whose children run into his arms when his hands are empty. <span>–Unknown</span>");
    quote.push("It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.  <span>–Ann Landers</span>");
    quote.push("If you want your children to turn out well, spend twice as much time with them, and half as much money. <span>–Abigail Van Buren</span>");
    quote.push("Build your own dreams, or someone else will hire you to build theirs. <span>–Farrah Gray</span>");
    quote.push("The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at. <span>–Jesse Owens</span>");
    quote.push("Education costs money.  But then so does ignorance. <span>–Sir Claus Moser</span>");
    quote.push("I have learned over the years that when one’s mind is made up, this diminishes fear. <span>–Rosa Parks</span>");
    quote.push("It does not matter how slowly you go as long as you do not stop. <span>–Confucius</span>");
    quote.push("If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough. <span>–Oprah Winfrey</span>");
    quote.push("Remember that not getting what you want is sometimes a wonderful stroke of luck. <span>–Dalai Lama</span>");
    quote.push("You can’t use up creativity.  The more you use, the more you have. <span>–Maya Angelou</span></span>");
    quote.push("Dream big and dare to fail. <span>–Norman Vaughan</span>");
    quote.push("Our lives begin to end the day we become silent about things that matter. <span>–Martin Luther King Jr.</span>");
    quote.push("Do what you can, where you are, with what you have. <span>–Teddy Roosevelt</span>");
    quote.push("If you do what you’ve always done, you’ll get what you’ve always gotten. <span>–Tony Robbins</span>");
    quote.push("Dreaming, after all, is a form of planning. <span>–Gloria Steinem</span>");
    quote.push("It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live. <span>–Mae Jemison</span>");
    quote.push("You may be disappointed if you fail, but you are doomed if you don’t try. <span>–Beverly Sills</span>");
    quote.push("Remember no one can make you feel inferior without your consent. <span>–Eleanor Roosevelt</span>");
    quote.push("Life is what we make it, always has been, always will be. <span>–Grandma Moses</span>");
    quote.push("The question isn’t who is going to let me; it’s who is going to stop me. <span>–Ayn Rand</span>");
    quote.push("When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. <span>–Henry Ford</span>");
    quote.push("It’s not the years in your life that count. It’s the life in your years. <span>–Abraham Lincoln</span>");
    quote.push("Change your thoughts and you change your world. <span>–Norman Vincent Peale</span>");
    quote.push("Either write something worth reading or do something worth writing. <span>–Benjamin Franklin</span>");
    quote.push("The only way to do great work is to love what you do. <span>–Steve Jobs</span>");


    var randomQuote = Math.floor(Math.random()*(quote.length));

    function printQuote(){
        $("p").append(quote[randomQuote]);
    }

    printQuote();

});